version: "3.9"

services:
  php:
      hostname: switchscreenshots
      container_name: sys-screenshot-uploader
      image: sys-screenshot-uploader
      restart: always
      volumes:
        - ${path}:/var/www/html/pics/
        - ${path}/config.php:/var/www/html/config.php
        - ${path}/log.log:/var/www/html/log.log
        # remove the # to open the port 80
     # ports:
        # - "80:80" 
      build:
        context: .
        dockerfile: Dockerfile
        target: base
# remove all under here if you dont use a network
networks:
  default:
    external:
      name: proxy-manager_default # change this to your desired network
